name: Build
on:
 schedule:
  - cron: "0 10 * * *"
 push:
  branches:
   - "*"
jobs:
 check:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4

   - name: Place Eruda File
     run: |
      curl https://cdn.jsdelivr.net/npm/eruda --output "./src/eruda.min.js";

   - name: Fetch Eruda Release Version
     run: |
      echo -n "VERSION_ERUDA=" >> $GITHUB_ENV;
      grep -o -m 1 -P "(?<=^\/\*! eruda )v[^ ]+" "./src/eruda.min.js" >> $GITHUB_ENV;

   - name: Build
     run: |
      npm install -g crx;
      crx pack -p "key.pem" "./src" -o "./mobile-devtools.crx";

   - name: Release with Notes
     uses: softprops/action-gh-release@v1
     with:
      files: "./mobile-devtools.crx"
      name: ${{ env.VERSION_ERUDA }}
      tag_name: ${{ env.VERSION_ERUDA }}
      generate_release_notes: true
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
